cargo install diesel_cli
cargo install cargo-tree
cargo install cargo-tree
cargo install structopt
cargo install cargo
cargo install petgraph
cargo install glob
cargo install opener
cargo install rustfix
cargo install home
cargo install curl
cargo install filetime
cargo install ignore
cargo install tar
cargo install bytesize
cargo install termcolor
cargo install git2
cargo install same-file
cargo install libz-sys
cargo install libnghttp2-sys
cargo install core-foundation-sys
cargo install libssh2-sys
cargo install walkdir
cargo install openssl-sys
cargo install globset
cargo install commoncrypto
cargo install heck
cargo install sized-chunks
cargo install humantime
cargo install typenum
cargo install ordermap
cargo install fixedbitset
cargo install commoncrypto-sys
cargo install unicode-segmentation
cargo install bstr
cargo install cargo-watch
cargo install cargo-do
cargo install regex
cargo install void
cargo install fnv
cargo install strsim
cargo install termcolor
cargo install glob
cargo install humantime
cargo install log
cargo install walkdir
cargo install filetime
cargo install atty
cargo install textwrap
cargo install fsevent
cargo install bstr
cargo install clap
cargo install notify
cargo install globset
cargo install watchexec
