cargo install diesel_cli
cargo install cargo-tree
cargo install cargo-tree
cargo install structopt
cargo install cargo
cargo install petgraph
cargo install glob
cargo install opener
cargo install rustfix
cargo install home
cargo install curl
cargo install filetime
cargo install ignore
cargo install tar
cargo install bytesize
cargo install termcolor
cargo install git2
cargo install same-file
cargo install libz-sys
cargo install libnghttp2-sys
cargo install core-foundation-sys
cargo install libssh2-sys
cargo install walkdir
cargo install openssl-sys
cargo install globset
cargo install commoncrypto
cargo install heck
cargo install sized-chunks
cargo install humantime
cargo install typenum
cargo install ordermap
cargo install fixedbitset
cargo install commoncrypto-sys
cargo install unicode-segmentation
cargo install bstr
